[package]
name = "advent-of-cuda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
cust = "0.3.2"

[workspace]
members = [
    "gpu",
]

[build-dependencies]
cuda_builder = "0.3.0"
